CREATE DATABASE BoletosDB;
USE BoletosDB;

CREATE TABLE XXXX(
	XXId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(30) NOT NULL,
    Email VARCHAR(50) NOT NULL ,
    Clave VARCHAR(40) NOT NULL 
);

ALTER TABLE XXXX
ADD CONSTRAINT UC_XXXX UNIQUE (Nombre);

CREATE TABLE Compras(
	CompraId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Total DOUBLE NOT NULL,
    FechaCompra DATETIME NOT NULL,
    UserId INT
);

CREATE TABLE dCompras(
	Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Precio DOUBLE NOT NULL ,
    Cantidad INT NOT NULL ,
    CompraId INT NOT NULL ,
    BoletoId INT NOT NULL
);


CREATE TABLE dSecciones (
	SeccionId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EventoId INT NOT NULL,
    Seccion Varchar(50) NOT NULL,
    Precio DOUBLE NOT NULL
);


CREATE TABLE CategoriaEventos (
	CategoriaId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Categoria VARCHAR(50) NOT NULL
);

CREATE TABLE Eventos (
	EventoId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    UserId INT,
    CategoriaId INT NOT NULL,
    FechaEvento DATETIME NOT NULL,
    BoletosDisponibles INT NOT NULL
);
CREATE TABLE Boletos (
	BoletoId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SeccionId INT NOT NULL,
    EventoId INT NOT NULL
);